/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siakadsmk;
import java.sql.Connection;

import java.sql.DriverManager;

import java.sql.ResultSet;

import java.sql.Statement;

import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class datasiswa extends javax.swing.JFrame {
     koneksi dbsetting;

    String driver,database,user,pass,userLogin;
    /**
     * Creates new form datasiswa
     */
    public datasiswa() {
        initComponents();
         dbsetting = new koneksi();

        driver = dbsetting.SettingPanel("DBDriver");

        database = dbsetting.SettingPanel("DBDatabase");

        user = dbsetting.SettingPanel("DBUsername");

       this.setSize(600,700);

       /** Langkah 1 disini :*/

        tblsiswa.setModel(tblModel);

        tampilkanData();
    }
    /** Langkah 2 disini :*/

        private javax.swing.table.DefaultTableModel tblModel=getDefaultTabel();

/** Langkah 3 disini :*/

private javax.swing.table.DefaultTableModel getDefaultTabel(){

    return new javax.swing.table.DefaultTableModel(

            new Object [][]{},

            new String []{"No. Urut","No.Induk","Nama Siswa","Alamat","No. Telp","Jurusan"}

            ){

                boolean[] canEdit = new boolean[]{

                    false,false,false,false,false,false

                };
public boolean isCellEditTable(int rowIndex, int columnIndex){

                    return canEdit[columnIndex];

            }

};
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnourut = new javax.swing.JTextField();
        txtnoinduk = new javax.swing.JTextField();
        txtnamasiswa = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnotelp = new javax.swing.JTextField();
        txtjurusan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsiswa = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        txtkeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Absensi Man 2 Model");

        jLabel1.setText("No. Urut");

        jLabel2.setText("No. Induk Siswa");

        jLabel3.setText("Nama Siswa");

        jLabel4.setText("Alamat");

        jLabel5.setText("No. Telepon");

        jLabel6.setText("Jurusan");

        tblsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsiswa);

        btntambah.setText("Tambah Data");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btndelete.setText("Hapus");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        txtkeluar.setText("Keluar");
        txtkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkeluarActionPerformed(evt);
            }
        });

        jLabel7.setText("ABSENSI MAN 2 MAKASSAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnourut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnoinduk, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btntambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtnourut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnedit))
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnoinduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnbatal)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnamasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndelete)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtkeluar)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btnsimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
          String stat="";

        try {

            Class.forName(driver);

            Connection koneksi = DriverManager.getConnection(database, user, "");

            Statement stt = koneksi.createStatement();

            String SQL = "insert into siswa values('"+txtnourut.getText()+"',"

                    + ""+"'"+txtnoinduk.getText()+"',"+"'"+txtnamasiswa.getText()+"',"

                    + ""+"'"+txtalamat.getText()+"',"+"'"+txtnotelp.getText()+"',"+"'"+txtjurusan.getText()+"')";

                stt.executeUpdate(SQL);

                data[0]=txtnourut.getText();

                data[1]=txtnoinduk.getText();

                data[2]=txtnamasiswa.getText();

                data[3]=txtalamat.getText();

                data[4]=txtnotelp.getText();

                data[5]=txtjurusan.getText();

          tblModel.insertRow(row, data);

            stt.close();

            koneksi.close();

        } catch (Exception exc) {

            System.err.println(exc.getMessage());

         }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkeluarActionPerformed
        // TODO add your handling code here:
         int keluar=JOptionPane.showConfirmDialog(null,"Benar Ingin Keluar?","Pertanyaan",

               JOptionPane.YES_NO_CANCEL_OPTION);

        if(keluar==0){

        System.exit(0);

        }
    }//GEN-LAST:event_txtkeluarActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        txtnourut.setText("");
        txtnoinduk.setText("");
        txtnamasiswa.setText("");
        txtalamat.setText("");
        txtnotelp.setText("");
        txtjurusan.setText("");
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
           tampilkanDataBatal();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void tblsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsiswaMouseClicked
        // TODO add your handling code here:
         if(evt.getClickCount()==1){

            tampilDiKolom();

    }
    }//GEN-LAST:event_tblsiswaMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
           try {

            Class.forName(driver);

            Connection koneksi = DriverManager.getConnection(database, user, "");

            Statement stt = koneksi.createStatement();

            String SQL = "delete from siswa where jurusan='"+txtjurusan.getText()+"'";

                  stt.executeUpdate(SQL);

                data[0]=txtnourut.getText();

                data[1]=txtnoinduk.getText();

                data[2]=txtnamasiswa.getText();

                data[3]=txtalamat.getText();

                data[4]=txtnotelp.getText();

                data[5]=txtjurusan.getText();

          tblModel.removeRow(row);

                 stt.close();

              koneksi.close();

        } catch (Exception exc) {

            System.err.println(exc.getMessage());

          }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
           try {

            Class.forName(driver);

            Connection koneksi = DriverManager.getConnection(database, user, "");

            Statement stt2 = koneksi.createStatement();

            String SQL2="update siswa set no_urut='"+txtnourut.getText()+"', no_induk='"+txtnoinduk.getText()+"', nama_siswa='"+txtnamasiswa.getText()+"', alamat='"+txtalamat.getText()+"',no_telp='"+txtnotelp.getText()+"',jurusan='"+txtjurusan.getText()+"' where jurusan='"+txtjurusan.getText()+"'";

                 stt2.executeUpdate(SQL2);

                data[0]=txtnourut.getText();

                data[1]=txtnoinduk.getText();

                data[2]=txtnamasiswa.getText();

                data[3]=txtalamat.getText();

                data[4]=txtnotelp.getText();

                data[5]=txtjurusan.getText();

                tblModel.removeRow(row);

                tblModel.insertRow(row,data);

            stt2.close();

            koneksi.close();

        } catch (Exception exc) {

            System.err.println(exc.getMessage());

          }
    }//GEN-LAST:event_btneditActionPerformed

    /**
     * @param args the command line arguments
     */
    public void tampilDiKolom(){

        row = tblsiswa.getSelectedRow();

        txtnourut.setText(tblModel.getValueAt(row, 0).toString());

        txtnoinduk.setText(tblModel.getValueAt(row, 1).toString());

        txtnamasiswa.setText(tblModel.getValueAt(row, 2).toString());

        txtalamat.setText(tblModel.getValueAt(row, 3).toString());

        txtnotelp.setText(tblModel.getValueAt(row, 4).toString());

        txtjurusan.setText(tblModel.getValueAt(row, 5).toString());

}

/**

* @param args the command line arguments

*/

/** Langkah 5 disini :*/

    int row=0;

    String data[] = new String[6];

    public final void tampilkanData(){

    String stat = "";

    try {

        Class.forName(driver);

        Connection koneksi = DriverManager.getConnection(database, user, "");

        Statement stt = koneksi.createStatement();

        String SQL = "Select * from siswa";

        ResultSet tampil = stt.executeQuery(SQL);

       

        while (tampil.next()){

            data[0] = tampil.getString(1);

            data[1] = tampil.getString(2);

            data[2] = tampil.getString(3);

            data[3] = tampil.getString(4);

            data[4] = tampil.getString(5);

            data[5] = tampil.getString(6);

        tblModel.addRow(data);

       

        txtnourut.setText(data[0].toString());

        txtnoinduk.setText(data[1].toString());

        txtnamasiswa.setText(data[2].toString());

        txtalamat.setText(data[3].toString());

        txtnotelp.setText(data[4].toString());

        txtjurusan.setText(data[5].toString());

        }

        tampil.close();

        stt.close();

        koneksi.close();

    } catch(Exception exc) {

        System.err.println(exc.getMessage());

    }

}

private void tampilkanDataBatal() {

        String stat="";

        int row2=0;

        String data2[]=new String[6];

        try {

            Class.forName(driver);

            Connection koneksi = DriverManager.getConnection(database, user, "");

            Statement stt = koneksi.createStatement();

            String SQL = "Select *from siswa order by no_urut asc";

            ResultSet tampil2=stt.executeQuery(SQL);

               

               while (tampil2.next()){

                data2[0]=tampil2.getString(1);

                data2[1]=tampil2.getString(2);

                data2[2]=tampil2.getString(3);

                data2[3]=tampil2.getString(4);

                data2[4]=tampil2.getString(5);

                data2[5]=tampil2.getString(6);

               

                txtnourut.setText(data2[0].toString());

                txtnoinduk.setText(data2[1].toString());

                txtnamasiswa.setText(data2[2].toString());

                txtalamat.setText(data2[3].toString());

                txtnotelp.setText(data2[4].toString());

                txtjurusan.setText(data2[5].toString());

               }

           tampil2.close();

           stt.close();

            koneksi.close();

        } catch (Exception exc) {

            System.err.println(exc.getMessage());

           

        }       

    }

 
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblsiswa;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtjurusan;
    private javax.swing.JButton txtkeluar;
    private javax.swing.JTextField txtnamasiswa;
    private javax.swing.JTextField txtnoinduk;
    private javax.swing.JTextField txtnotelp;
    private javax.swing.JTextField txtnourut;
    // End of variables declaration//GEN-END:variables
}
